spring:
  application:
    name: web
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=agro_trade
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: agro_trade
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active:

server:
  port: 8080

agro_trade:
  web:
    upload:
      image:
        directory:
          user: "D:/Project/agro_trade/upload_images/"
          news:
          product:

logging:
  file:
    name: D:/Project/agro_trade/log/agro-trade-web.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 3
      clean-history-on-start: true

  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.example.studentportalspring.controller: DEBUG
