spring:
  application:
    name: web
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=agro_trade
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database: PostgreSQL
    properties:
      hibernate:
        default_schema: agro_trade
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active:

jwt:
  secret-key: k8v9x2mP7qL5tR4jH8gF6dS3aZ1xC5vB7nM9pQ2wE4rT6yU8iO0pL3wY6uI9oP2lK4jH8gF6dS3aZ1xC5vB7nM9pQ2wE4rT6yU8iO0pL
  access-expiration: 900000
  refresh-expiration: 604800000

server:
  port: 8080

app:
  upload:
    dir: D:\Project\agro_trade\storage
  base-url: http://localhost:8080


logging:
  file:
    name: D:/Project/agro_trade/log/agro-trade-web.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 3
      clean-history-on-start: true

  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.example.studentportalspring.controller: DEBUG


client:
  chat-service:
    url: http://localhost:8081
  notification:
    url: http://localhost:8082

rest:
  connect-timeout: 5000
  read-timeout: 10000