package am.agrotrade.common.enums;

public enum ErrorCode {

    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USER_NOT_VERIFIED,
    USER_ALREADY_VERIFIED,

    INVALID_REFRESH_TOKEN,
    INVALID_VERIFICATION_CODE,
    VERIFICATION_CODE_EXPIRED,

    INVALID_CREDENTIALS,
    INVALID_OLD_PASSWORD,
    INVALID_USER_ROLE,

    PASSPORT_NOT_FOUND,
    PASSPORT_ALREADY,

     AN_UNEXPECTED_ERROR;

}